### ISSUE TITLE
remove "type": "module" in `package.json`

### ISSUE THREAD

**Issue by yaquawa** [jhurliman/node-rate-limiter#75]
Currently, `"type": "module"` is not supported well in webpack 5 or ts-node, in `package.json` it already has "exports" and "module" fields set properly, so no need the `"type": "module"` field. 

same issue is also happening with the [just-performance](https://github.com/jhurliman/just-performance)

**Comment by jhurliman** [comment]
@yaquawa are you able to provide a small repro of the issue? Do you have a webpack setup where the build currently fails, but removing `"type": "module"` causes the build to succeed? I tested with the latest webpack while reorganizing the project, but I'm sure there are configurations that I missed which is why it would be helpful for me to see for future regression testing.

**Comment by ali-sharif** [comment]
[This](https://github.com/TypeStrong/ts-node/issues/935) is the issue which causes `ts-node` to trip up when it encounters libraries with  the `"type": "module"` field set

**Comment by jhurliman** [comment]
Fixed in https://github.com/jhurliman/node-rate-limiter/pull/79
