### ISSUE TITLE
Rate Limiting does not happen for particular IP address

### ISSUE THREAD

**Issue by xxxazxxx** [jhurliman/node-rate-limiter#8]
Limits = 40/day
Once 40 requests are served irrespective of the IP Addresses, It redirects to the 429 view.
So even the visitor whose visiting the site for the first time, is redirected to 429.
Can we have rate limiting for every IP address?

```
var RateLimiter = require('limiter').RateLimiter;
var limiter = new RateLimiter(40, 'day', true);  // fire CB immediately

app.use(function (req, res, next) {
  if ((req.headers["user-agent"].indexOf("Googlebot") != -1) || req.url == "/429")
    next();
  else
    limiter.removeTokens(1, function(err, remainingRequests) {
      if (remainingRequests < 0) {
        res.redirect('/429');
      } else {
        next();
      }
    });
});
```

**Comment by bugs181** [comment]
This is the answer I was looking for. I would of never found it had I not checked the closed issues. I was about to request this as a feature myself. To the author of this repo, I would like to request that you add the above snippet to the README for others looking for this answer. I was actually about to turn away from this project until I saw this issue. Thanks to @eirikfro for sharing the above snippet!

**Comment by boboci9** [comment]
Hi @eirikfro,

I tried using your code 
```
checkBy = req.headers.app_id;
		rate = 416;
		period = 'hour';
		waitFor = 10000;
		checkRateLimit(checkBy, rate, period);
 checkRateLimit = function(checkBy, rate, period)
 {
 	var RateLimiter = Npm.require('limiter').RateLimiter;
		var cache = Npm.require('memory-cache');
 	if (cache.get(checkBy)){
			var cachedLimiter = cache.get(checkBy); 
			if (cachedLimiter.getTokensRemaining()>1){
				cachedLimiter.removeTokens(1, function(){});
				cache.put(checkBy, cachedLimiter, waitFor);
				return;
			}
			console.log("error");
			throw new Error('Too many requests for the app_id: ' + checkBy + '!');
		}
		else {
			var cachedLimiter = new RateLimiter(rate, period); 
			cache.put(checkBy, cachedLimiter, waitFor); 
			return;
		}
 }
```
but when I make a while cycle for 500 requests they all get passed. Could you tell me what am I doing wrong, also how should I use the waitFor parameter in the cache.put function because I want to lock the user requests for an hour if they exceed this period but if I use `waitFor=360000` it still let's me pass all requests??
Thanks in advance.

**Comment by bugs181** [comment]
@boboci9 It's kind of hard to diagnose your problem without seeing how you're calling `checkRateLimit`.

From what you've explained; It sound's like you're running into the typical async problem. If you're in a `while` loop, then the limiter never has a chance to reduce itself before the next iteration runs. You need to wait for this method to return before continuing onto the next loop iteration.

    for (...) {
        checkRateLimit(...)
    }

That won't work how you think it does. Because as previously stated, the method is called before the async function has had time to complete. You need to set up some sort of flow control.

**Comment by eirikfro** [comment]
As @bugs181 mention, this seems like javascript async problems. Javascript is great, but might seem very strange if you are used to other languages where code is fired consecutively. :) I think @bugs181 solution will help you.

**Comment by boboci9** [comment]
Hi guys thanks for the answers, my calls are actually API calls so my while cycle is calling API calls, I thought that should work.
I will try it with the tryRemoveTokens, but my gratest issue was that if I set a rate of 10 calls per hour everything worked after the 10th it stopped but if I set 10 calls per second than are the issues presenting and it will let me call all the 30 API calls that I have in the while.
